### ISSUE TITLE
Compatibility with Spyder 3

### ISSUE THREAD

**Issue by ogencoglu** [joonro/Spyder-Color-Themes#1]
Couple of changes needed for Spyder 3:

- the field 'occurence' is changed to 'occurrence' ,e.g., github/occurrence = #ffff99
- a new field 'name' is introduced, e.g,. tomorrow/name = Tomorrow
- the field currentcell is missing in github theme

**Comment by joonro** [comment]
Thanks for this. I will change these when I get a chance.

**Comment by joonro** [comment]
Fixed by f69a50ec06a10b3f016b9fb99f86919c18396a2d. Thank you again.

**Comment by joonro** [comment]
Actually fixed by 18545b7d4de976dee35c0d1bc02ffea3c37c3ffa. :)
